server:
  port: 8081

kafka:
  bootstrap-servers: localhost:29092
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 74018402649-i033lk3mh6md9979u9k8a6n650afoh4d.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
        provider:
          provider:
            google:
              authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
              token-uri: https://oauth2.googleapis.com/token
              user-info-uri: https://openidconnect.googleapis.com/v1/userinfo

  datasource:
    url:  jdbc:mysql://localhost:3308/patient?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
aws:
  region: us-east-1
  credentials:
    accessKey: AKIAWPPO6BYCQNL6XPWW
    secretKey: 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
  s3:
    bucket-name: my-springboot-bucket

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        deregister: true
        health-check-path: /actuator/health
        health-check-interval: 10s


