server:
  port: 8084

spring:
  redis:
    host: localhost
    port: 6379
  cache:
    redis:
      time-to-live: 600000 # 10 minutes

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        register: true
        deregister: true
        health-check-path: /actuator/health
        health-check-interval: 10s
    vault:
      uri: http://172.26.192.1:8200
      token: hvs.bk8Bg6eBYeP9FBQOQ330C39a
      kv:
        enabled: true
        backend: secret
      application-name: mysql_vault

  datasource:
    url: jdbc:mysql://172.26.192.1:3308/userschema?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fetchfromvault
    password: fetchfromvault

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update  # Options: none, validate, update, create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE

latest-prop: "DEV"
