spring:
  cloud:
    vault:
      uri: http://172.26.192.1:8200
      token: hvs.hAqBCU2VQqcBAJVCrm4NEX4b
      kv:
        enabled: true
        backend: secret
      application-name: mysql_vault
  datasource:
    url: jdbc:mysql://172.26.192.1:3308/userschema?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: fetchfromvault
    password: fetchfromvault
    jpa:
      hibernate:
        ddl-auto: update  # Options: none, validate, update, create-drop
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8084

latest-prop: "test"