spring:
  cloud:
    vault:
      uri: http://host.docker.internal:8200
      token: hvs.1GFqk1myqw3o0t9Uh50KGCv1
      kv:
        enabled: true
        backend: secret
      application-name: mysql_vault
  datasource:
    url: jdbc:mysql://host.docker.internal:3308/userschema?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update  # Options: none, validate, update, create-drop
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8084

latest-prop: "test"