spring:
  datasource:
    url: jdbc:mysql://host.docker.internal:3308/userschema?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: ${mysql_vault.user_name}  #${vault.secret.data.data.mysql.username}  # Corrected path
    password: ${mysql_vault.password} #${vault.secret.data.data.mysql.password}  # Corrected path
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto: update  # Options: none, validate, update, create-drop
      show-sql: true
      database-platform: org.hibernate.dialect.MySQLDialect
  config:
    import: vault://secret/data/mysql_vault
  cloud:
    vault:
      uri: http://127.0.0.1:8200
      token: hvs.1GFqk1myqw3o0t9Uh50KGCv1
      kv:
        enabled: true
        backend: secret
        default-context: mysql_vault  # The context name (path) where your keys are stored
server:
  port: 8084

latest-prop: "test"